include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Conformance code must be explicit about types.
    always_declare_return_types: error

linter:
  rules:
    - prefer_final_locals
    - prefer_final_in_for_each
    - avoid_dynamic_calls
    - unawaited_futures
